all: default
default: debug

release:
	+$(MAKE) -C balcao release
	+$(MAKE) -C ger_cl release
debug:
	+$(MAKE) -C balcao debug
	+$(MAKE) -C ger_cl debug

clean:
	+$(MAKE) -C balcao clean
	+$(MAKE) -C ger_cl clean
